global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: Prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          grupo: 'Prometheus'

  - job_name: ApiProduto
    static_configs:
      - targets: ['13.89.1098.26']
        labels:
          grupo: 'AspNetCore'