apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: api-deployment 
spec:
  selector:
    matchLabels:
      app: api 
  template:
    metadata:
      labels:
        app: api 
    spec:
      containers:
        - name: api 
          image:  kubedevjean.azurecr.io/pedelogo-catalogo:v1.0.0
          ports:
          - containerPort: 80
            name: http 
          - containerPort: 443 
            name: https # IMAGE PULL POLICE É A REGRA PARA PULL DE IMAGEM
            # Always = sempre faz o pull da imagem
          imagePullPolicy: Always
          # ENVFROM É PARA BUSCAR AS VARIAVEIS DE AMBIENTE DE ALGUM LUGAR
          # NESSE CASO DO CONFIGMAP
          envFrom: 
            - configMapRef:
                name: api-configmap
          # AGORA VOU PEGAR SO O VALOR DO SECRET DO MONGO PARA AS VARIAVEIS
          # QUE JA EXISTEM NELE
          env: 
            - name: Mongo__User 
              # PEGO O VALOR DO SECRET DO MONGO DE ACORDO COM A CHAVE
              valueFrom:
                secretKeyRef:
                  # CHAVE DO SECRET MONGO DB
                  key: MONGO_INITDB_ROOT_USERNAME
                  # NOME DO SECRET
                  name: mongodb-secret
            - name: Mongo__Password
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: mongodb-secret
      imagePullSecrets:
        - name: acr-kubedev