apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template: 
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb 
          image:  mongo:4.2.8
          ports:
           - containerPort: 27017
          # ENVFROM É PARA BUSCAR AS VARIAVEIS DE AMBIENTE DE ALGUM LUGAR
          # NESSE CASO DO CONFIGMAP, COMO AS CHAVES SÃO IGUAIS FAÇO PRO REFERENCIA
          envFrom:
            - secretRef:
                name: mongodb-secret