apiVersion: v1
kind: Secret 
metadata:
  name: mongodb-secret 
type: Opaque 
data: 
  # OS VALORES DAS CHAVES EU EXECUTO NO BASH O BASE64 DELES
  # ➜  echo -n "mongouser" | base64                                  
  MONGO_INITDB_ROOT_USERNAME: bW9uZ291c2Vy
  # ➜  echo -n "mongopwd" | base64 
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ29wd2Q=